# Spaces root handle: @space
server {
    listen       80;
    server_name  @space;

    root   /Users/i830671/git/spaces-sites/@space;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
