# Spaces handle: nostrops@space
server {
    listen       80;
    server_name  nostrops@space;

    # root   /Users/i830671/git/spaces-sites/nostrops@space;
    root   /Users/i830671/git/nostrops-space;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
