# Spaces handle: nostrops@space
server {
    listen       80;
    server_name  nostrops@space;

    root   /var/www/nostrops-space;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }
}
